# Generated by Django 2.2.4 on 2019-09-09 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vibes', '0004_auto_20190909_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='content_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='design_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='usability_rating',
            field=models.DecimalField(blank=True, decimal_places=1, default=0, max_digits=3),
        ),
    ]
